server:
  port: 8011
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: EUREKA_CONSUMER #这里是另一个中心的地址